services:
  productbackendapp: 
    container_name: productbackendapp
    image: productbackend:1.0.0
    ports: 
      - '3001:3001'
  productfrontendapp:
    container_name: productfrontendapp
    image: productfrontend:1.0.0
    ports: 
      - '80:80'